  GNU nano 2.5.3                                   File: /var/log/apache2/error.log

[Fri Apr 06 14:53:46.628821 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:18134]     dbapi = dialect_cls.dbapi(**dbapi_args)
[Fri Apr 06 14:53:46.628825 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:18134]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.628833 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:18134]     import psycopg2
[Fri Apr 06 14:53:46.628843 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:18134] ImportError: No module named psycopg2
[Fri Apr 06 14:53:46.648920 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134] mod_wsgi (pid=8520): Target WSGI script '/var/www/cat$
[Fri Apr 06 14:53:46.648933 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134] mod_wsgi (pid=8520): Exception occurred processing WS$
[Fri Apr 06 14:53:46.648945 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134] Traceback (most recent call last):
[Fri Apr 06 14:53:46.648966 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/var/www/catalog/catalog.wsgi", line 6, in <m$
[Fri Apr 06 14:53:46.648984 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     from catalog import app as application
[Fri Apr 06 14:53:46.648990 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/var/www/catalog/catalog/__init__.py", line 6$
[Fri Apr 06 14:53:46.648999 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     from database_setup import Base, Store, Inventory$
[Fri Apr 06 14:53:46.649004 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/var/www/catalog/catalog/database_setup.py", $
[Fri Apr 06 14:53:46.649011 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     engine = create_engine('postgresql://catalog1:pas$
[Fri Apr 06 14:53:46.649016 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.649025 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     return strategy.create(*args, **kwargs)
[Fri Apr 06 14:53:46.649030 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.649036 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     dbapi = dialect_cls.dbapi(**dbapi_args)
[Fri Apr 06 14:53:46.649041 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.649048 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134]     import psycopg2
[Fri Apr 06 14:53:46.649060 2018] [wsgi:error] [pid 8520:tid 140011048052480] [remote 18.219.47.135:18134] ImportError: No module named psycopg2
[Fri Apr 06 14:53:46.669409 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830] mod_wsgi (pid=8520): Target WSGI script '/var/www/cat$
[Fri Apr 06 14:53:46.669423 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830] mod_wsgi (pid=8520): Exception occurred processing WS$
[Fri Apr 06 14:53:46.669436 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830] Traceback (most recent call last):
[Fri Apr 06 14:53:46.669448 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/var/www/catalog/catalog.wsgi", line 6, in <m$
[Fri Apr 06 14:53:46.669466 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     from catalog import app as application
[Fri Apr 06 14:53:46.669472 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/var/www/catalog/catalog/__init__.py", line 6$
[Fri Apr 06 14:53:46.669481 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     from database_setup import Base, Store, Inventory$
[Fri Apr 06 14:53:46.669486 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/var/www/catalog/catalog/database_setup.py", $
[Fri Apr 06 14:53:46.669493 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     engine = create_engine('postgresql://catalog1:pas$
[Fri Apr 06 14:53:46.669498 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.669515 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     return strategy.create(*args, **kwargs)
[Fri Apr 06 14:53:46.669521 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.669528 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     dbapi = dialect_cls.dbapi(**dbapi_args)
[Fri Apr 06 14:53:46.669532 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]   File "/usr/local/lib/python2.7/dist-packages/sqlalc$
[Fri Apr 06 14:53:46.669540 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830]     import psycopg2
[Fri Apr 06 14:53:46.669551 2018] [wsgi:error] [pid 8520:tid 140010947241728] [remote 18.219.47.135:15830] ImportError: No module named psycopg2
